### ISSUE TITLE
Can't set Port:?

### ISSUE THREAD

**Issue by ferventgeek** [cesanta/mongoose-os-ide#2]
mos is working fine on my mac, but in VS code I can't set the port value. Clicking "Port <click to set>" opens a value entry box at the top, but putting a value in there does nothing. Tab/click-away/enter.. nada. Maybe I'm doing something super dumb.

Update: You can set it in .vscode/settings.json and restart. So it's maybe an editor bug. Anyway great plugin!

**Comment by Gonkers** [comment]
I believe this issue is a duplicate of #1

**Comment by ferventgeek** [comment]
Still seeing it after the update, but it's easily fixable so no worries.

**Comment by poolski** [comment]
>Update: You can set it in .vscode/settings.json and restart. So it's maybe an editor bug. Anyway great plugin!

What exactly did you do to fix this? I've tried to set the port by hand to a known working port (works with the `mos` CLI) but I'm still getting errors

**Comment by ferventgeek** [comment]
I'm going to close this as the config workaround.. works fine.

**Comment by poolski** [comment]
@ferventgeek it's not clear what the workaround _is_ though - could you please elaborate?
